
def max(num1 : int , num2 : int) -> int:
    if num1 > num2:
        return num1

    return num2        


# max(1,"3")    this will cause error
print(max(1,3)) # this is good

x: int = 0
